package com.abdelhakim.cnc.login.models;

public enum NomMatiere {
    MATHEMATIQUES_I,
    MATHEMATIQUES_II,
    PHYSIQUE_I,
    PHYSIQUE_II,
    CHIMIE,
    INFORMATIQUE,
    CULTURE_ARABE_ET_TRADUCTION,
    FRANCAIS,
    ANGLAIS,
    SCIENCES_INDUSTRIELLES,
    TECHNOLOGIES_ET_SCIENCES_INDUSTRIELLES
}